version: "3"

services:

  mongo1:
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors --dbpath /data/db --nojournal --oplogSize 16 --noauth
    ports:
      - 27017:27017
    volumes:
      - ${DATA_DIR}/mongo1:/data/db

  mongo2:
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors --dbpath /data/db --nojournal --oplogSize 16 --noauth
    ports:
      - 27018:27017    
    volumes:
      - ${DATA_DIR}/mongo2:/data/db

  mongo3:
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors --dbpath /data/db --nojournal --oplogSize 16 --noauth
    ports:
      - 27019:27017    
    volumes:
      - ${DATA_DIR}/mongo3:/data/db